// The mod's own artwork, embedded in the DLL (Art\*.png / *.jpg, generated by mod\art\make_art.py) and decoded once
// into sprites: the crest, the 5 x 5 atlas of white glyphs (tinted where they are used), the chamfered 9-slice panel,
// the soft gold glow for the focused element, and the menu's backdrop. Everything degrades to "no sprite" - a flat
// Image - when the texture API or a resource is missing, so the menu still works without its art.
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using Il2CppInterop.Runtime.InteropTypes.Arrays;
using UnityEngine;

namespace YazsCompanion
{
    internal static class Art
    {
        /// <summary>The order of the glyphs in glyphs.png (rows of five, top to bottom): keep in step with make_art.py.</summary>
        public static readonly string[] Glyphs =
        {
            "crosshair", "bullets", "blast", "flame", "bolt",
            "snow", "flask", "blade", "turret", "shield",
            "cross", "paw", "gear", "magnet", "chevrons",
            "clock", "skull", "link", "coin", "heart",
            "hash", "radio", "eye", "diamond", "up"
        };
        const int Cell = 128, Grid = 5;

        static readonly Dictionary<string, Texture2D> _tex = new Dictionary<string, Texture2D>();
        static readonly Dictionary<string, Sprite> _sprites = new Dictionary<string, Sprite>();

        static Texture2D Texture(string file)
        {
            Texture2D t;
            if (_tex.TryGetValue(file, out t)) { try { if (t != null && t.width > 0) return t; } catch { } _tex.Remove(file); }
            try
            {
                var asm = Assembly.GetExecutingAssembly();
                string res = null;
                foreach (var n in asm.GetManifestResourceNames()) if (n.EndsWith("." + file, StringComparison.OrdinalIgnoreCase)) { res = n; break; }
                if (res == null) { Plugin.Logger.LogInfo("[art] " + file + " is not embedded"); return null; }
                byte[] bytes;
                using (var s = asm.GetManifestResourceStream(res)) using (var ms = new MemoryStream()) { s.CopyTo(ms); bytes = ms.ToArray(); }
                t = new Texture2D(2, 2, TextureFormat.RGBA32, false);
                t.hideFlags = HideFlags.HideAndDontSave; t.wrapMode = TextureWrapMode.Clamp; t.filterMode = FilterMode.Bilinear;
                if (!ImageConversion.LoadImage(t, (Il2CppStructArray<byte>)bytes)) { Plugin.Logger.LogInfo("[art] " + file + " not decoded"); return null; }
                _tex[file] = t;
                return t;
            }
            catch (Exception e) { Plugin.Logger.LogInfo("[art] " + file + ": " + e.Message); return null; }
        }

        static Sprite Cached(string key, Func<Sprite> make)
        {
            Sprite s;
            if (_sprites.TryGetValue(key, out s)) { try { if (s != null && s.texture != null) return s; } catch { } _sprites.Remove(key); }
            try { s = make(); if (s != null) { s.hideFlags = HideFlags.HideAndDontSave; _sprites[key] = s; } return s; }
            catch (Exception e) { Plugin.Logger.LogInfo("[art] " + key + ": " + e.Message); return null; }
        }

        static Sprite Whole(string file)
        {
            return Cached(file, () => { var t = Texture(file); return t == null ? null : Sprite.Create(t, new Rect(0, 0, t.width, t.height), new Vector2(0.5f, 0.5f), 100f); });
        }

        static Sprite Sliced(string file, float border)
        {
            return Cached(file + "#9", () =>
            {
                var t = Texture(file); if (t == null) return null;
                return Sprite.Create(t, new Rect(0, 0, t.width, t.height), new Vector2(0.5f, 0.5f), 100f, 0, SpriteMeshType.FullRect, new Vector4(border, border, border, border));
            });
        }

        public static Sprite Emblem { get { return Whole("emblem.png"); } }
        public static Sprite Backdrop { get { return Whole("backdrop.jpg"); } }
        /// <summary>A stand-in for the field behind the DISPLAY tab's readout preview: dark ground, a few bright effects.</summary>
        public static Sprite Field { get { return Whole("field.jpg"); } }
        /// <summary>9-slice: chamfered corners and a gold hairline around a dark body (border 48 of 128 px).</summary>
        public static Sprite Panel { get { return Sliced("panel.png", 48f); } }
        /// <summary>9-slice: a soft gold glow ring for the focused element; lay it 30 units outside the element.</summary>
        public static Sprite Glow { get { return Sliced("glow.png", 60f); } }

        /// <summary>A white glyph by name (tint it with Image.color); null when unknown.</summary>
        public static Sprite Glyph(string name)
        {
            int i = Array.IndexOf(Glyphs, name ?? "");
            if (i < 0) return null;
            return Cached("glyph:" + name, () =>
            {
                var t = Texture("glyphs.png"); if (t == null) return null;
                int col = i % Grid, row = i / Grid;
                // texture rows count from the bottom
                return Sprite.Create(t, new Rect(col * Cell, t.height - (row + 1) * Cell, Cell, Cell), new Vector2(0.5f, 0.5f), 100f);
            });
        }
    }
}
